//
//  Generated file. Do not edit.
//
//  This file is regenerated by `flutter run` / `flutter build windows`
//  whenever the set of plugins changes. This stub is a placeholder so the
//  CMake target compiles before the first real `flutter build`.
//

#include "generated_plugin_registrant.h"

void RegisterPlugins(void* /* windows_registrar */) {
  // No plugins registered yet; Flutter will re-generate this file.
}
